defaults:
  - agent: dummy
  - test_suites: nocrash_dense
actors:
  hero:
    agent: dummy
    reward:
      entry_point: reward.valeo_action:ValeoAction
    terminal:
      entry_point: terminal.valeo_no_det_px:ValeoNoDetPx
agent:
  dummy:
    entry_point: opal.agents.dummy_agent:DummyAgent
    hack_throttle: true
    target_speed: 6.0
    resolution: 1.0
    longitudinal_pid_params: [0.5, 0.025, 0.1]
    lateral_pid_params: [0.75, 0.05, 0.0]
    threshold_before: 7.5
    threshold_after: 5.0
carla_sh_path: /home/mkdusgml/carla_ws/carla0910/CarlaUE4.sh
log_level: INFO
host: localhost
port: 2000
seed: 42
no_rendering: false
kill_running: true
resume: true
wb: true
wb_project: hsovp
wb_name: eval_hsovp
wb_notes: null
wb_tags: ['hsovp', 'baseline', 'evaluation', 'nocrash_dense', ]
log_video: true