data_algo: "roach_bc"
data_benchmark: "leaderboard1"
data_town: ["Town04"]
seed: 42

model:
  state_dim: 192
  action_dim: 3
  latent_dim: 8 
    
dataset:
  num_workers: 4
  train_batch_size: 32
  val_batch_size: 32
  val_ratio: 0.2
  trajectory_length: 10
  distance_threshold: 0.8
  discrete_option: 6

train:
  device: "cuda:1"
  resume: false
  resume_ckpt_dir: ""
  num_epochs: 1000
  num_evals: 10
  eval_frequency: 10
  lr: 0.0001
  
verbose: true
wb: true
wandb_project: "hso-vp"
wandb_name: "train_hsovp"
wandb_tag: ["baseline", "hsovp", "roach_bc", "leaderboard1"]