data:
    algo: "hsovp"
    data_town: ["Town01","Town03", "Town04", "Town06"]
    num_workers: 4
    train_batch_size: 128
    val_batch_size: 128
    val_ratio: 0.2
    trajectory_length: 10

model:
    obs_dim: 192
    action_dim: 3
    latent_dim: 8
    latent_as_action: true
    q_hidden_dim: 32
    v_hidden_dim: 32
    obs_feature_dim: 64

train:
    algo: "iql"
    device: "cuda:0"
    seed: 42
    num_epochs: 1000
    eval_frequency: 10
    q_lr: 0.001
    v_lr: 0.001
    policy_lr: 0.001
    max_steps: 10000
    tau: 0.7
    beta: 3.0
    discount: 0.99
    alpha: 0.005
    num_random: 10
    temperature: 1.0
    cql_alpha: 1.0
    z_high: 1.0
    z_low: -1.0

resume: false
resume_ckpt_dir: ""
verbose: true
wb: true
wandb_project: "hso-vp"
wandb_name: "train_hsovp_high_level_policy_iql"
wandb_tag: ["Town01","Town03", "Town04", "Town06", "iql", "hsovp-igh-level-policy"]