data:
    data_town: ["Town01", "Town03", "Town04", "Town06"]
    num_workers: 4
    train_batch_size: 256
    val_batch_size: 256
    val_ratio: 0.2
    length: 10
    discrete_option: 10

model:
    obs_dim: 192
    action_dim: 2
    latent_dim: 10
    obs_feature_dim: 64
    hidden_dim: 128
    gru_hidden_dim: 64
    gru_layers: 2
    discrete_option: 10

train:
    device: "cuda:1"
    seed: 42
    num_epochs: 1000
    eval_frequency: 10
    lr: 0.0001
    kl_weight: 1.0
    beta_y: 0.01
    beta_z: 0.01

resume: true
resume_ckpt_dir: "20250321_084309"
verbose: true
wb: true
wandb_project: "hso-vp"
wandb_name: "hsovp"
wandb_tag: ["hsovp", "baseline", "leaderboard1", "Town01", "Town03", "Town04", "Town06"]