data:
    data_town: ["Town01", "Town03", "Town04", "Town06"]
    num_workers: 4
    train_batch_size: 128
    val_batch_size: 128
    val_ratio: 0.2
    trajectory_length: 10

model:
    obs_dim: 192
    action_dim: 2
    latent_dim: 10
    latent_as_action: false
    q_hidden_dim: 32
    v_hidden_dim: 32
    obs_feature_dim: 128

train:
    algo: "iql"
    device: "cuda:1"
    seed: 42
    num_epochs: 1000
    eval_frequency: 10
    q_lr: 0.0001
    v_lr: 0.0001
    policy_lr: 0.0001
    max_steps: 10000
    tau: 0.7
    beta: 0.5
    discount: 0.99
    alpha: 0.005
    num_random: 10
    temperature: 1.0
    cql_alpha: 1.0
    high: 1.0
    low: -1.0

resume: true
resume_ckpt_dir: "20250319_225607"
verbose: true
wb: true
wandb_project: "offline_rl"
wandb_name: "train_iql"
wandb_tag: ["leaderboard1", "Town01", "Town03", "Town04", "Town06", "iql", "baseline"]